### ISSUE TITLE
🤖  Mettre en place la CI/CD pour déployer l'application

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#10]
## Besoin
L'application doit pouvoir être déployé de manière continue sans avoir besoin d'action manuelle (c'est à dire créer l'archive et la mettre sur le Play Store). Cela permettra aussi la réalisation de #9 

## Solution
Dans un premier temps mettre semantic-release pour l'incrémentation de numéro de version.
Ensuite mettre en place une solution pour déployer sur le PlayStore (Fastlane ou autre).

## Tache

- [x] Mettre en place Semantic-Release
- [ ]  Mettre en place Fastlane

**Comment by adriens** [comment]
>  semantic-release 

Jolissa

**Comment by adriens** [comment]
:mechanical_arm: :smile_cat:

**Comment by lschaeffer313** [comment]
Semantic-Release utilisé avec succès.
@adriens j'ai utilisé l'outil [act](https://github.com/nektos/act) pour tester la CI Github en local.
Cela m'a évité de tester la CI en faisant plusieurs commit.

**Comment by adriens** [comment]
> Semantic-Release utilisé avec succès.

:muscle:  :sunglasses: Mais je vois pas de brance `develop`, passe nous voir qu'on te fasse le feedback de pourquoi on as basculé sur ce mode

> @adriens j'ai utilisé l'outil [act](https://github.com/nektos/act) pour tester la CI Github en local.

Cool ça, faudra que tu nous montres ça !

**Comment by lschaeffer313** [comment]
Je passerais vous voir cette aprem 😉

**Comment by adriens** [comment]
Yes, on a fait ça...c'était bien sympa la discussion sur les flow git :people_holding_hands:

**Comment by lschaeffer313** [comment]
Mission accomplie :

<img width="1499" alt="image" src="https://user-images.githubusercontent.com/28922072/193438620-3546e178-a11b-4355-82d4-348b9b7c5c4c.png">

<img width="1187" alt="Capture d’écran 2022-10-02 à 15 57 47" src="https://user-images.githubusercontent.com/28922072/193438610-61fcd3cd-59f3-4511-b806-65aa90a83702.png">

**Comment by lschaeffer313** [comment]
@adriens 4 minutes pour déployé l'appli c'est long mais plus rapide que d'autres solutions
@3079rod check ça

**Comment by adriens** [comment]
très élégant comme processus : tu pourrais me dropper une video du processus de bout en bout @lschaeffer313 :grey_question: :pray:

**Comment by lschaeffer313** [comment]
Dès que Google à validé l'appli, je te fais une vidéo qui explique le process avec Fastlane.
Pour semantic-relase, on à déjà une vidéo dessus mais un rappel ne fait pas de mal 😉

**Comment by adriens** [comment]
Yes, une video commentée de ce pipeline, de bout en bout sera au top 🚀
