### ISSUE TITLE
:octocat: Mauvais emoji pour affichage téléphone :octocat: :skull: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#103]
![image](https://user-images.githubusercontent.com/5235127/210158938-9fed49c9-49c7-4481-851a-fa61517a7d01.png)

**Comment by lschaeffer313** [comment]
![image](https://user-images.githubusercontent.com/28922072/210470447-e3d88b67-0642-490f-a828-9df2ff41962f.png)
