### ISSUE TITLE
:bulb:  Adopt a lean and flat modern logo ;) :sunglasses: 

### ISSUE THREAD

**Issue by darwiin** [lschaeffer313/domaine-nc-mobile#113]
I really love how the app is designed but I think it would be better with a flatter and simplier logo.

I suggest starting from **.nc**. 

My sample below use Ubuntu font (I love it),  but feel free to choose a better one and colorize it the way you want.

<img width="69" alt="image" src="https://user-images.githubusercontent.com/318998/210498714-d4946856-b5fd-40c1-b13e-581bad71cbe3.png">

This logo could also support _Android 13 themed icons_

What do you think ?

**Comment by adriens** [comment]
très bonne idée @darwiin (cf https://github.com/lschaeffer313/domaine-nc-mobile/issues/105)

**Comment by adriens** [comment]
>  colorize it the way you want.

:point_right: Maybe @lschaeffer313 @HakumenNC with the thick colortheme black/yello which gives the feeling of powa :muscle:

**Comment by adriens** [comment]
> This logo could also support Android 13 themed icons

Sure :+1:

**Comment by adriens** [comment]
@sverolle do you have some skills to achieve that kind of things ?

**Comment by adriens** [comment]
:point_right: Issue pinned :+1:

**Comment by adriens** [comment]
Hey @darwiin , would you plan to deliver us some content ? We will start working on [🚀 Domaines.nc : "New Horizons "](https://github.com/lschaeffer313/domaine-nc-mobile/milestone/3) and wonder if we should load this issue on it :thought_balloon:

**Comment by adriens** [comment]
@lschaeffer313 , je tente une approche pour avancer sur le logo et l'icone de l'app : 


Tentative de générer avec de l'IA cf : 

- [Tweet](https://twitter.com/rastadidi/status/1621967069783924736)
- [🚀 Introducing IconifyAI 🚀](https://twitter.com/saviomartin7/status/1621801021025419264)
- https://www.iconifyai.com/

![image](https://user-images.githubusercontent.com/5235127/216788152-acd7b5f6-a454-485e-88cf-a6f3e2a6b84b.png)

**Comment by darwiin** [comment]
@adriens I could propose something 😉

**Comment by adriens** [comment]
🤩  @darwiin ⚡

**Comment by adriens** [comment]
BIM @darwiin  dans ce cas
![image](https://user-images.githubusercontent.com/5235127/216879685-e560efc3-7d81-47aa-8f08-1bbfaa9a2d88.png)

**Comment by adriens** [comment]
:wave:  @darwiin , des news :grey_question:

**Comment by darwiin** [comment]
Pas sur que ça puisse faire un bon logo finalement 
https://www.canva.com/design/DAFamEcQ_ak/LHZl9f1QfImWTf-wrfkr5w/edit?utm_content=DAFamEcQ_ak&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
![domaines_nc](https://user-images.githubusercontent.com/318998/218897619-7472d8d3-5ede-4a73-b314-eb10df1ca9e1.png)

**Comment by adriens** [comment]
Avec un fond blanc ptet ?

**Comment by adriens** [comment]
et u njaune plus flashy ?

**Comment by darwiin** [comment]
![domaine2](https://user-images.githubusercontent.com/318998/218906919-5e9af938-8020-46ba-91c9-f54f5da53914.png)

**Comment by adriens** [comment]
:laughing: C radical... ça me fait une drôle d'impression....

**Comment by darwiin** [comment]
![domaine_w](https://user-images.githubusercontent.com/318998/218907155-592f47fb-3fac-4821-a3c8-0d81dbb4d771.png)
![domaine2_white](https://user-images.githubusercontent.com/318998/218907160-54f47852-8110-4487-809b-568e0c29f885.png)

**Comment by darwiin** [comment]
En blanc c'est mieux

**Comment by adriens** [comment]
> En blanc c'est mieux

Yes, y'a pas photo :zap:

**Comment by adriens** [comment]
mais le point c super strange, ça ressemble pas du tout à une fin d'url :thinking:

**Comment by darwiin** [comment]
Oui, j'avais un truc qui semblait bon en tête, mais à la réalisation c'est nettement moins convaincant

**Comment by adriens** [comment]
celui ci est vraiment bien. On pourrait voir ce que çadonne avec le texte plus gros ?

![image](https://user-images.githubusercontent.com/5235127/218909630-86d48673-ba83-47bf-9187-76de64682357.png)

**Comment by darwiin** [comment]
![domaine_big](https://user-images.githubusercontent.com/318998/218950659-8dc80b63-9c7d-4481-b9b5-c31a5adaf50f.png)

**Comment by adriens** [comment]
@lschaeffer313 , t peux nous donner un preview en mode icon d'app mobile ? avec la dernière version ?

**Comment by lschaeffer313** [comment]
Je te fais ça.

**Comment by adriens** [comment]
Pour le WE, kep cool :sunglasses: :cocktail:

**Comment by adriens** [comment]
J'enquillserai sur ça dans la foulée : 

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/134

**Comment by lschaeffer313** [comment]
IL EST MAGNIFY :
<img width="449" alt="image" src="https://user-images.githubusercontent.com/28922072/218986517-6569713b-9fe6-4859-b3ff-44f4654910d7.png">

**Comment by adriens** [comment]
PUTAIN @darwiin , c'est BEAU :heavy_heart_exclamation:

**Comment by lschaeffer313** [comment]
Sur Android :
<img width="431" alt="image" src="https://user-images.githubusercontent.com/28922072/218987409-12720f2b-fb4c-4b4b-801e-7852032c1bbd.png">

**Comment by lschaeffer313** [comment]
Avec la bonne résolution !!!
Merci @darwiin.

**Comment by adriens** [comment]
:star_struck:  @darwiin :clap: :muscle:

**Comment by lschaeffer313** [comment]
@adriens je sais pas pour toi, mais pour moi c'est validé direct !!!

**Comment by adriens** [comment]
@darwiin a fait une PR pour le logo ?

**Comment by adriens** [comment]
> @adriens je sais pas pour toi, mais pour moi c'est validé direct !!!

NET :exclamation: 

:point_up: Ca serait de la :bomb: si @darwiin  : 

1. Créait une branche sur cette issue
2. Faisait une PR vers develop

**Comment by lschaeffer313** [comment]
J'ai déjà fait le changement de mon côté... et il y a un bon paquet 😅
<img width="637" alt="image" src="https://user-images.githubusercontent.com/28922072/218988135-d6b2be8b-310d-428c-9023-3c41bab9cf70.png">

**Comment by adriens** [comment]
LOL ça envoie du pâté ces outils, c'est vraiment méchant 🙀

**Comment by adriens** [comment]
:point_right: 

- https://github.com/lschaeffer313/domaine-nc-mobile/pull/156

**Comment by tamere-allo-peter** [comment]
Perso je trouve que le point devant `nc` manque énormément de contraste sur toutes les images ci-dessus...

**Comment by adriens** [comment]
> Perso je trouve que le point devant `nc` manque énormément de contraste sur toutes les images ci-dessus...

:thinking: Maintenant que tu le dis

**Comment by darwiin** [comment]
![domaine_black](https://user-images.githubusercontent.com/318998/219255604-a458451d-37a0-4511-a086-47409773ebb5.png)

**Comment by tamere-allo-peter** [comment]
Bien mieux à mon avis, mais ce n'est que mon avis.

**Comment by darwiin** [comment]
@adriens @lschaeffer313 vos avis ;)

**Comment by adriens** [comment]
Je plussoie 💯 ... et ça : 

✔️ Rappelle e thème Dark
✔️ On voit le point

![image](https://user-images.githubusercontent.com/5235127/219261725-e1e1efcd-1e25-4eb8-9ccc-983cf2c450e4.png)

..

**Comment by darwiin** [comment]
@lschaeffer313 @adriens je peux essayer de faire une PR, mais comme j'ai pas les outils pour générer ça va me prendre du temps.

**Comment by adriens** [comment]
@lschaeffer313 , où @darwiin pourrait dropper le logo à minima ?

**Comment by adriens** [comment]
.. sur la repo ?

**Comment by darwiin** [comment]
Résolution de l'image et répertoire d'upload, je peux m'en occuper ;)

**Comment by adriens** [comment]
C'est cool, comme ça on aura une PR de toi... c'est qd même lamoindre des choses 😸

**Comment by lschaeffer313** [comment]
Tu peux faire une PR en remplaçant icon.png dans lib/assets/icon.
Je m'occuperais du reste pour générer les fichiers 😁

**Comment by adriens** [comment]
> Je m'occuperais du reste pour générer les fichiers grin

OUaiiiisss c'est la Ci qui le fait :trollface:

**Comment by lschaeffer313** [comment]
La CI a la Mano comme on l'appelle dans le milieu 🤣

**Comment by adriens** [comment]
t'as pas un genre de makfiele pour ça ? BEUAAHHHHHHHHH
