### ISSUE TITLE
:loudspeaker:  Exécuter la campagne de tests Testeum :champagne: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#115]
Pour faire suite à : 

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/114

![image](https://user-images.githubusercontent.com/5235127/211771369-e7ff1556-8c05-458d-8e44-db8dff92f520.png)

**Comment by ZoeThivet** [comment]
Alors, ça se passe bien ? :D

**Comment by lschaeffer313** [comment]
Beaucoup de retour 😊
Certaines campagnes ne sont pas terminées, dès que ce sera le cas je créerai les issues associées aux bug trouvée.

**Comment by adriens** [comment]
CADEWIZZZZZZZZZZZZZ :open_mouth:

**Comment by adriens** [comment]
:loudspeaker: https://github.com/lschaeffer313/domaine-nc-mobile/milestone/2

**Comment by lschaeffer313** [comment]
Campagnes terminées, je passe à la création d'issues.

**Comment by adriens** [comment]
Une bien belle moisson :star_struck:
