### ISSUE TITLE
🐛 (Testeum) Nice to have : Placeholder

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#118]
Il est possible que des utilisateurs saisissent mal un domaine (en mettant par exemple https://) -> il faudrait mieux les guider.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/28922072/213886436-dabf36bd-14f6-4b27-8fdf-039c074990ab.png">

**Comment by adriens** [comment]
Super bonne idée ça :heavy_heart_exclamation:
