### ISSUE TITLE
🐛 (Testeum) Auto-correction clavier

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#121]
Lorsque le clavier du smartphone propose 'gouvernement" et qu'on choisi l'auto-implémentation, ça rajoute un espace à la fin. Du coup la recherche ne s'effectue pas. Pour un "novice" en informatique, il ne pensera pas à enlever l'espace.
<img width="194" alt="image" src="https://user-images.githubusercontent.com/28922072/213886807-99f3c555-0707-4d7e-b1be-8e2ca24d88d5.png">

**Comment by adriens** [comment]
Punaise, tous ces petits bugs qui gênent l'UX, très bien joué :sunglasses:
