### ISSUE TITLE
🐛 (Testeum) Erreur inconnu :bomb: 

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#122]
Il faudrait écrire "Erreur inconnuE" 
L'erreur a été provoquée par le collage de 100 paragraphes de Lorem Ipsum dans la barre de recherche. 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/28922072/213887152-37faad3b-c930-4287-9554-e62283efded0.png">

**Comment by lschaeffer313** [comment]
@adriens on pourrait appliquer plusieurs correction pour cette issue : 

- On limite le nombre de caractère à un nombre fixe (il faudrait connaître le nombre que peut prendre possiblement un nom de domaine)
- On enlève la possibilité de mettre des espaces et cela corrigerait possiblement aussi l'issue #121.

**Comment by lschaeffer313** [comment]
Bon ben 😅

<img width="863" alt="image" src="https://user-images.githubusercontent.com/28922072/213889574-468146d3-124c-4d46-999e-f67fff30bba6.png">

Vérifié sur le net :

<img width="918" alt="image" src="https://user-images.githubusercontent.com/28922072/213889628-93a092d7-1cce-4438-8e75-812f6125d1be.png">

**Comment by adriens** [comment]
:point_right:  Ton idée de tester avec Chat-GPT : c'est GENIAL !!! J'adore l'approche

> L'erreur a été provoquée par le collage de 100 paragraphes de Lorem Ipsum dans la barre de recherche.

Bordel, fallait penser à faire un truc dans ce genre ! Je me demande si on devrait pas blinder aussi côté API :thought_balloon:

**Comment by lschaeffer313** [comment]
@adriens peut-être mettre une limitation comme pour l'appli mobile mais sur l'API maybe ?
Si supérieur à 63, 400 Bad Request avec une explication du pourquoi de l'erreur ?

**Comment by adriens** [comment]
> @adriens peut-être mettre une limitation comme pour l'appli mobile mais sur l'API maybe ? Si supérieur à 63, 400 Bad Request avec une explication du pourquoi de l'erreur ?

Oui, exactement une Bad Request :heavy_check_mark:

**Comment by adriens** [comment]
Je fais l'issue de ce pas :zap:

**Comment by adriens** [comment]
:point_down: 

- https://github.com/opt-nc/domaine-nc-api/issues/325

**Comment by adriens** [comment]
A priori on déploiera le fix semaine prochaine :rocket:
