### ISSUE TITLE
🐛 (Testeum) Orthographe : "4 année(s) restante"

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#123]
Il faudrait homogénéiser. 
4 année(s) restante(s) par exemple 
Ou, mieux, adapter le texte en fonction du nombre d'années, pour éviter les parenthèses.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/28922072/213887545-1a5b577d-b220-483b-be15-695c41bde037.png">

**Comment by adriens** [comment]
Y'a pas une lib genre `ICU4J` en dart ?

**Comment by tamere-allo-peter** [comment]
@lschaeffer313 idée en l'air : ce serait sans doute bien d'indiquer, outre le nom des serveurs DNS leurs adresses IP telle qu'extraite de la BDD domaine.nc (et pas via une résolution DNS). En effet, la zone NC est truffée d'erreur (au moins une quarantaine) où des noms de serveurs DNS sont indiqués dans le même domaine que celui choisi, mais sans aucune adresse IP et sans que l'enregistrement correspondant aux serveurs DNS concernés n'ait été ajouté dans la zone **.nc**. De ce fait le domaine n'est normalement pas résolvable car il manque l'enregistrement `glue` correspondant dans la zone **.nc**. 

Par exemple, si pour le domaine **exemple.nc** la BDD contient **ns1.exemple.nc** et **ns2.exemple.nc** (donc même domaine) mais sans qu'aucune IP soit associée dans la BDD et sans que ces enregistrements soient connus dans la zone **.nc** (pas d'enregistrement `glue` correspondant), alors ce domaine ne sera pas résolvable via le DNS (problème classique de l'oeuf et de la poule). Il serait bien dans ce cas d'indiquer qu'il y a une erreur.

Peut-être qu'une autre possibilité, apportant la même information, serait d'effectuer une requête DNS pour voir si les noms de serveurs DNS indiqués sont résolvables (afficher un rond vert ou une coche V verte) ou pas (afficher un rond rouge ou une coche X rouge)...

à toi de voir mais ce serait bien d'afficher ce genre d'info.

hth...

**Comment by lschaeffer313** [comment]
@tamere-allo-peter effectivement ce genre d'infos serait intéressant à ajouter. @adriens m'avait parlé d'une librairie permettant de la vérification.
@adriens avons nous un ticket qui parle de cela ? Ou faut-il en créer un ?

**Comment by lschaeffer313** [comment]
> Y'a pas une lib genre `ICU4J` en dart ?

Je ne l'avais pas vu. Je vais check.

**Comment by adriens** [comment]
> @adriens avons nous un ticket qui parle de cela ? Ou faut-il en créer un ?

Si , c'était dans les [discussion](https://github.com/lschaeffer313/domaine-nc-mobile/discussions)
 : 

- https://github.com/lschaeffer313/domaine-nc-mobile/discussions/106
- https://github.com/lschaeffer313/domaine-nc-mobile/discussions/108
- https://github.com/lschaeffer313/domaine-nc-mobile/discussions/107
