### ISSUE TITLE
:telescope:  Upgrade to Flutter 3.7 :sparkles: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#130]
# :grey_question: A propos

[Flutter 3.7.0](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.7.0) a été releasé cette semaine et prépare une nombre important de grosses évolutions, dont des performances graphiques supérieures.

:point_right: Il serait bon d'upgrader vers cette dernière version.

# :dart: Actions

- [x] https://github.com/lschaeffer313/domaine-nc-mobile/pull/128
- [x] Upgrader en [Flutter 3.7.0](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.7.0) 
- [ ] Publier sur le store

# :bookmark_tabs: Ressources

- :zap: [Très courte démo de 3.7](https://youtu.be/XEfCYh3F3_Y)
- :newspaper_roll: [Pourquoi upgrader](https://youtu.be/LwgvrPg330Q)
- :memo:  [What’s next for Flutter](https://medium.com/flutter/whats-next-for-flutter-b94ce089f49c)
- :cinema: 3' [Flutter 3.7 // Flutter Forward 2023 Recap - The Future of Flutter & Dart](https://youtu.be/gJ2Eg7q7QuU)
- :bookmark: [Official Flutter 3.7.0 release notes (from Google)](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.7.0)
- :memo:  [Material 3 updates, iOS improvements, and much more!](https://medium.com/flutter/whats-new-in-flutter-3-7-38cbea71133c)
- :bird: ["The future of Flutter:"](https://twitter.com/FlutterDev/status/1618300167786233856)

# :rocket: What's next

![image](https://user-images.githubusercontent.com/5235127/214761583-33cc5558-011b-4148-ad1b-60de0a00a376.png)

**Comment by lschaeffer313** [comment]
Hello @adriens, de notre côté il n'y a rien à faire on utilise déjà le dernier SDK flutter pour builder l'application (via la GitHub Action associé) je vais quand même la remplacer par stable pour ne pas avoir de bugs ou autre qu'il peut y avoir ^^.

**Comment by lschaeffer313** [comment]
Il y a juste le sdk sur le poste de travail à mettre à jour (via Homebrew ou autre)

**Comment by adriens** [comment]
> Il y a juste le sdk sur le poste de travail à mettre à jour (via Homebrew ou autre)

Excellent ! Tu as jeté un oeil aux supports ? J'en ai ajouté un super court et vraiment bien foutu

**Comment by adriens** [comment]
Du coup, tu fermes l'issue puisque #136 :grey_question:

**Comment by lschaeffer313** [comment]
Yes

**Comment by adriens** [comment]
oh yes :clap:
