### ISSUE TITLE
UX Tweak

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#132]
# :grey_question: A propos

Actuellement l'écran d'un domaine gâche de l'espace en haut alors qu'il en manque en bas : 

![image](https://user-images.githubusercontent.com/5235127/214773221-5ebc110f-2ab0-4306-bdcc-22e1ec2191ae.png)

# :bulb: Proposition

L'idée est de faire remonter d'un cran le nom de domaine : 

![image](https://user-images.githubusercontent.com/5235127/214773376-9f847319-eb9e-459d-a267-9e78fc52449f.png)

Afin de combler la zone vide : 

![image](https://user-images.githubusercontent.com/5235127/214773434-77891a3f-c654-4ce2-bb48-9a225c2c5321.png)

# :moneybag: Gains

- On gagnera de l'espace en bas, ce sera plus agréable, moins "tassé"

**Comment by lschaeffer313** [comment]
@adriens après changement :
<img width="353" alt="image" src="https://user-images.githubusercontent.com/28922072/215617429-4a91a6f2-9399-4bd7-a302-75b7b440ecfc.png">

**Comment by adriens** [comment]
:grey_question: Du coup tu reprend pas : 

- La taille de fonte
- L'incongraphie

![image](https://user-images.githubusercontent.com/5235127/215636861-ec702c93-ff3c-44b4-bd8f-39c6eb81c3d1.png)

**Comment by lschaeffer313** [comment]
<img width="354" alt="image" src="https://user-images.githubusercontent.com/28922072/215673735-018deec3-6c9b-4144-8863-bfb95d2f9da1.png">

**Comment by adriens** [comment]
OH YES C BON CA :heavy_heart_exclamation:

**Comment by adriens** [comment]
Je laisse semantic fermer quand tu releaseras :+1:

**Comment by adriens** [comment]
[`v1.2.4`](https://github.com/lschaeffer313/domaine-nc-mobile/releases/tag/v1.2.4) livrée : 

![image](https://user-images.githubusercontent.com/5235127/215867756-7ce7a946-8d9e-4bf7-bf72-963696ffcab6.png)

![image](https://user-images.githubusercontent.com/5235127/215867728-fd657b40-1ba9-4ffb-95fc-8c48ca990136.png)

**Comment by adriens** [comment]
:clap: l'écran est super clean maintenant, y compris la zone basse :muscle: 

![image](https://user-images.githubusercontent.com/5235127/215868064-2fd93e9c-98d9-4cda-bfb2-e2391c208a9a.png)

**Comment by adriens** [comment]
On est passés de : 

![image](https://user-images.githubusercontent.com/5235127/215868298-89de5a78-d59b-4c26-af2e-4b1967173423.png)


à :point_down: 

![image](https://user-images.githubusercontent.com/5235127/215868366-6672d0a4-ad7c-4aca-9c7f-c29b5aafa260.png)
