### ISSUE TITLE
:nerd_face: Aligner l'icone de l'app avec le style dark/yellow

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#133]
# :grey_question: A propos

Actuellement le syle de l'app dark/yellow fait un tabac... mais l'icone fait toujours un peu veilllot.

# :bulb: Idée

Bacsuler sur le même thème dark yellow

# :ticket: Issues liées

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/113

**Comment by lschaeffer313** [comment]
Je pense que vue que la #113 est clôturé, on peut faire de même avec celle-ci @adriens ?
