### ISSUE TITLE
:shield:  Upgrade to  3.7.1

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#139]
# :grey_question: Context

[A bunch of useful fixes in Flutter 3.7.1, because our product is built by humans, and artisanally-crafted software has a natural grain.](https://twitter.com/timsneath/status/1620911609995739148)

![image](https://user-images.githubusercontent.com/5235127/216218188-c0f1164b-11d0-46be-b8a6-5a3f4c7dab09.png)

# :dart: Actions

- [x] Upgrade stack poste de dev
- [x] Upgrade CI
- [x] Release sur les stores

# :bookmark: Related issues

- :ticket:  https://github.com/lschaeffer313/domaine-nc-mobile/issues/130
- :octocat:  [Hotfixes to the Stable Channel](https://github.com/flutter/flutter/wiki/Hotfixes-to-the-Stable-Channel#371-feb-1-2022)

**Comment by adriens** [comment]
et celle-ci @lschaeffer313 ?

**Comment by lschaeffer313** [comment]
Yep

**Comment by adriens** [comment]
C coool
![image](https://user-images.githubusercontent.com/5235127/220009341-c6c3b17c-30eb-46bb-96e7-dd0ea7566b08.png)
