### ISSUE TITLE
:policeman:  Lint Flutter ? :shield: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#142]
### Discussed in https://github.com/lschaeffer313/domaine-nc-mobile/discussions/141

<div type='discussions-op-text'>

<sup>Originally posted by **adriens** February 11, 2023</sup>
@lschaeffer313 , tu lintes Le source flutter au fait ?

- https://medium.com/flutter-senior/using-dart-linter-for-cleaner-code-from-config-to-github-workflow-d17e2d5f5997
- https://dart.dev/guides/language/analysis-options
</div>

**Comment by adriens** [comment]
:zap: @lschaeffer313

**Comment by lschaeffer313** [comment]
🤩
<img width="454" alt="image" src="https://user-images.githubusercontent.com/28922072/218674586-e503bb7f-1dc2-4261-a12f-a276dba51176.png">
Beaucoup d'options !!!
<img width="589" alt="image" src="https://user-images.githubusercontent.com/28922072/218674648-17df70ca-59d3-44f6-9c49-a20df3d35349.png">

**Comment by adriens** [comment]
OH YES :clap: :sunglasses:
