### ISSUE TITLE
🔖 Ajouter url playstore au about

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#174]
![image](https://github.com/lschaeffer313/domaine-nc-mobile/assets/5235127/dda9fcc5-11ad-4d0f-abb7-0fc6b5b91459)

**Comment by adriens** [comment]
Tout bête... mais pratique en vrai 😅

**Comment by lschaeffer313** [comment]
Done !!
<img width="343" alt="image" src="https://github.com/lschaeffer313/domaine-nc-mobile/assets/28922072/84a9dcd9-6497-4c46-a185-81458797b4a1">
