### ISSUE TITLE
:link: Ajouter lien playstore au About

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#176]
![image](https://github.com/lschaeffer313/domaine-nc-mobile/assets/5235127/c3ea2b05-926b-4a72-81c7-28b2d4f854d0)

**Comment by lschaeffer313** [comment]
Done !!
<img width="343" alt="image" src="https://github.com/lschaeffer313/domaine-nc-mobile/assets/28922072/84a9dcd9-6497-4c46-a185-81458797b4a1">

**Comment by adriens** [comment]
Stylé bro 💪
