### ISSUE TITLE
Mise à jour de dépendance : Dependabot

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#18]
# Besoin
Afin de garder l'application à jour, il faut un utilitaire qui préviendra lorsque qu'une mise à jour d'une des dépendances  de l'application.

# Solution
Dependabot va permettre de créer des pull-request afin de mettre à jour les dépendances de l'application

**Comment by adriens** [comment]
YES, c'est très bon ça @lschaeffer313 :muscle:

**Comment by adriens** [comment]
EH EH, joli la maintenance :sunglasses:
