### ISSUE TITLE
:rocket: Bascule vers Google APIGEE :partying_face: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#198]
# :grey_question: Contexte

Depuis plus d'un an (cf [🔖 Get started with Apigee Management ⏱️](https://dev.to/optnc/get-started-with-apigee-management-55dg)), l'OPT-NC a investi vers une solution de portail d'API industriel, performant et sécurisé.

**:point_right: Le but de cette issue est de basculer les appels sur ce portal d'API.**

# :dart: Action

- [x] :man_student: Lire et regarder  [🔑 APIGEE 101: onboarding & authentication](https://dev.to/optnc/apigee-101-onboarding-authentication-1ghl) afin de comprendre comment consommer les APIs sur le [portail de l'OPT-NC](https://apigee-optnc-prd-api.apigee.io/)
- [x] Faire quelques test d'appels via par exemple [`httpie`](https://httpie.io/)
- [x] Basculer les appels d'app mobile vers apigee (dégager les appels à rapidapi)
- [x] Releaser la nouvelle version
- [x] Valider que la nouvelle version de l'app mobile est bien fonctionnelle

# :moneybag: Bénéfices

- Davantage de sécurité
- Davantage  de métrique
- Préparation du décommissionnement rapidapi (au profit de apigee)

# :bookmark_tabs: Ressources

- [Google Apigee series sur `DEV.to`](https://dev.to/adriens/series/21192)
- [🔑 APIGEE 101: onboarding & authentication](https://dev.to/optnc/apigee-101-onboarding-authentication-1ghl)
- Portail développeur : https://apigee-optnc-prd-api.apigee.io/

**Comment by lschaeffer313** [comment]
@adriens Nouvelle version déployé. 1.4.1.
A tester dans la soirée ou demain (ou plus tard en fonction de Google 😅)

**Comment by lschaeffer313** [comment]
@adriens par contre j'ai remarqué des erreurs CORS quand j'ai testé les API sur le portail d'api.
J'ai été sur ce site : https://apigee-optnc-prd-api.apigee.io/docs/domaine-nc/1/routes/actuator/get
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/3cbd9f29-edf3-44d2-acf0-8b357d85416c">

**Comment by adriens** [comment]
ARRF, galère, yes on a eues, et depuis un client REST àa dit quoi ?

**Comment by adriens** [comment]
Mas tu as réussi à consommer depis l'appli ?

**Comment by adriens** [comment]
- https://github.com/lschaeffer313/domaine-nc-mobile/pull/199/

**Comment by adriens** [comment]
yes, tu pointes dessus.

Je veux bien un usecase de reproduction pour le souci CORS :pray:

**Comment by adriens** [comment]
j'attends la notif sur mon mobile
:hourglass_flowing_sand:

**Comment by lschaeffer313** [comment]
> yes, tu pointes dessus.
> 
> Je veux bien un usecase de reproduction pour le souci CORS 🙏

Pour le usecase :

1. Créer une App
2. Autoriser l'App d'accéder aux API de Domaine.nc
3. Appuyer sur Execute et voir le message d'erreur

Code d'erreur dans la console Développeur sous Safari :
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/f5051a2d-3fed-4635-9a77-c2704a937da8">

**Comment by lschaeffer313** [comment]
> Mas tu as réussi à consommer depis l'appli ?

Yes

**Comment by MelanieGault** [comment]
j'ai fais les changements pour refleter les nouveaux parametrages de cors. Ce n'etait pas encore fait pour domaine-nc.

en prod : 
<img width="1949" alt="image" src="https://github.com/user-attachments/assets/3c3abde4-926e-42b2-979b-9d6c07a40a57">

**Comment by adriens** [comment]
:raised_hands: @MelanieGault 
:point_right: @lschaeffer313 tu confirmes les fix ?

**Comment by lschaeffer313** [comment]
@adriens Je confirme 👍🏻 
<img width="1170" alt="image" src="https://github.com/user-attachments/assets/24126236-0e90-4b5c-a2ba-5486868101a2">

**Comment by adriens** [comment]
Excellent !
J'attends la maj sur le playstore !
Punaise la première app mobile sur apigee est open source et en flutter !!!

**Comment by lschaeffer313** [comment]
@adriens tu valide la nouvelle version ?

**Comment by adriens** [comment]
J'ai pas eu la notification de maj

**Comment by adriens** [comment]
Je desinstalle ré installe

**Comment by adriens** [comment]
Ça marche ![Screenshot_20240925_075206.jpg](https://github.com/user-attachments/assets/7eb25f45-cc6e-48da-9cba-cb766ce92c5d)

**Comment by adriens** [comment]
Faudrait pouvoir choper la version courante de l'application non ?

**Comment by lschaeffer313** [comment]
> Ça marche ![Screenshot_20240925_075206.jpg](https://private-user-images.githubusercontent.com/5235127/370466409-7eb25f45-cc6e-48da-9cba-cb766ce92c5d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyMTE2OTMsIm5iZiI6MTcyNzIxMTM5MywicGF0aCI6Ii81MjM1MTI3LzM3MDQ2NjQwOS03ZWIyNWY0NS1jYzZlLTQ4ZGEtOWNiYS1jYjc2NmNlOTJjNWQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MjRUMjA1NjMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGQzMTFhZjcwOTU5ZjlhYWZhNTcyNzJkOWM4NmNlMDFjY2QwMWRiODNlOTA2YzdlY2Q3YTQyYTIyMTBkY2Y3ZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.GEWTebLX3005oxW9Ckf5YIC86QKtC3CUFYktlE07akU)

Good 👌🏻

**Comment by lschaeffer313** [comment]
> Faudrait pouvoir choper la version courante de l'application non ?

Tu peux l'avoir l'information de la version actuel sur le téléphone mais pas au sein de l'application.
Il faudra qu'on fasse une autre issue pour savoir ou le positionner pour avoir l'info dans l'appli.
