### ISSUE TITLE
Compléter topic du About

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#20]
Ajouter les topics : 

![image](https://user-images.githubusercontent.com/5235127/194536438-c4e9b29d-1424-4cd7-84ce-441fff2f15a5.png)

- `domaine-nc`
- `flutter`
- `new-caledonia`
- `nouvelle-caledonie`

**Comment by lschaeffer313** [comment]
😎 🙌
<img width="365" alt="image" src="https://user-images.githubusercontent.com/28922072/194537761-d68123c0-947d-4073-b3dc-a9c4c039478c.png">

**Comment by adriens** [comment]
Yes, voila, maintenant on a ceci : un topic bien clean que nous allons pouvoir valoriser par exemple sur notre carto 

https://github.com/topics/domaine-nc


![image](https://user-images.githubusercontent.com/5235127/194659444-e24b1d3e-667a-4ae4-88a5-47975f65134c.png)
