### ISSUE TITLE
🚨 Crash de l'application sur les domaines protégé 🚨

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#21]
## 🐛 Problème
Lorsqu'on consulte un domaine qui est protégé (du style **_gouvernement.nc_**), l'application ne répond plus.
## 👉 Cause
L'application s'attend à ce que l'API de domaine-nc-api retourne un objet avec des champs non null par l'endpoint /name/extension.
## 😵 Solution temporaire
Rendre les champs nullables afin que l'application ne rentre plus en erreur.
## 👍 Solution pérenne dans le temps
Faire en sorte que l'API renvoi des champs non-nullable.
On pourrait imaginer qu'il renvoi des chaînes de caractères vides.
## ✊ Action à faire dans tout les cas
Prendre en compte le cas des domaines protégé dans l'application.

## ❓Pourquoi cette issue ?
Dart implémente ce qu'on appelle le null safety ✅. Cela prémunit d'accéder à des références d'objet ou de champs qui sont null. Cela incite (ou plutôt oblige) le développeur a écrire du code sans risque d'avoir des erreurs de type **NullPointerException**.

**Comment by lschaeffer313** [comment]
Les champs en question :
![image](https://user-images.githubusercontent.com/28922072/194674157-7ae9e3c1-a936-4b6c-b8ed-74a5a8ba5b99.png)

**Comment by lschaeffer313** [comment]
@adriens je créer une issue sur domaine-nc-api ?

**Comment by adriens** [comment]
> @adriens je créer une issue sur domaine-nc-api ?

:rofl: J'allais te demander, yes :pray:

**Comment by lschaeffer313** [comment]
@adriens ticket mise à jour suite à notre discussion 😁

**Comment by adriens** [comment]
> @adriens ticket mise à jour suite à notre discussion grin

Excellent :muscle:

**Comment by spencer-forrest-opt** [comment]
> Dart implémente ce qu'on appelle le null safety ✅

@adriens, @3079rod  un peu comme [KOTLIN](https://kotlinlang.org/docs/null-safety.html), non ?  😆

**Comment by lschaeffer313** [comment]
@spencer-forrest-opt Exactement

**Comment by adriens** [comment]
> > Dart implémente ce qu'on appelle le null safety ✅
> 
> @adriens, @3079rod un peu comme [KOTLIN](https://kotlinlang.org/docs/null-safety.html), non ?  😆

LOOOOOOOL ENORME !!!! OUIIIIII, excellent @spencer-forrest-opt @3079rod @sverolle 🤣 🤣 🤣 🤣 🤣 🤣

**Comment by adriens** [comment]
:clap:
