### ISSUE TITLE
:memo: Article DEV.to : Maintenir et releaser en continu avec Fastlane/Github 📽

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#22]
# :grey_question: Contexte

Un pipeline de BUILD/deploy full cloud, automatisé et élégant a été mis en oeuvre sur ce projet. Il est donc temps d'en expliquer les détails et bénéfices afin de capitaliser cette connaissance et de la partager.

# :dart: Actions

- [x] Produire un article DEV.to dédié
- [x] Créer une video commentée de démo complète détalllant un flot complet  : de l'issue  à l abranche, ... à la PR puis la release via la CI, fastlane... et voir arriver la version sur le store
- [x] Intérer la video à l'article
- [x] Publier l'article
- [x] Socialiser sur l'article

## :movie_camera:  Explication sur la video

Suite à #10, une vidéo d'explication serait la bienvenue afin d'expliquer comment fonctionne le déploiement avec l'outil fastlane
Elle doit être simple et explicite afin que tous puissent comprendre :

- Le pourquoi : Le problème que l'on cherche à résoudre
- Le comment : La solution utilisé pour parvenir au résultat
- Les avantages : Ce que cette solution peut apporter

:warning:  **: NB : j'aimerais bien avoir la video afin de la rajouter à la [playlist ](https://youtube.com/playlist?list=PL7GdrgVAWcDilGJGeNuVdvCM-lSmt5DNT) :pray:** 

## :bookmark_tabs: Ressources

- :memo:  [📢 DOMAINE.NC mobile v1.0.7 sur le PlayStore 🛍️](https://dev.to/adriens/domainenc-mobile-v107-sur-le-playstore-5741)
- :memo: [Série dédiée sur `DEV.to`](https://dev.to/adriens/series/20723)
- :tv: [Playlist dédiée Youtube](https://youtube.com/playlist?list=PL7GdrgVAWcDilGJGeNuVdvCM-lSmt5DNT)

**Comment by adriens** [comment]
:ok_hand: Très bien picthé @lschaeffer313

**Comment by lschaeffer313** [comment]
@adriens Je viens d'avoir une très bonne idée💡
Au lieu de juste faire un vidéo, on pourrait en profiter pour en faire un DevOps Lab.
Je m'explique, je dois faire une démonstration aux archis de la solution GitHub avec l'intégration AppFlow
On pourrait en profiter pour leur montrer aussi Fastlane et présenter les avantages et les inconvénient des deux solutions.
Même si je penche plus pour Fastlane qui est open-source et future proof en cas de changement de techno mobile.

**Comment by adriens** [comment]
Hello @lschaeffer313 , bien sûr :star_struck: 

Je verrai bien le plan suivant (grosses mailles)

1. Poser le contexte, la problématique et l'objectif exact du DEVOPS-LABS (ici, démontrer comment automatiser le build en continu et cloud d'une app mobile Flutter)
2. Détailler pourquoi Flutter
3. Contexte projet Open Innovation : une API publique sur marketplace
4. Poser le mode projet : ressources humaines et IT
5. Démo live d'ajout d'une feature/fix sur Git puis delivery dans l'app sur marketplace
6. Conclusion et surtout timing et ressources humaines investies  (temps passé, formation, compétences en début vs. compéténces en fin)

Voila, par-contre, je pense que le timing serait plutôt : 

- 30' démo
- 30' discussion

Ensuite : 

- Démo video pour publique
- Article DEV.to

On pourra faire les reviews de ta prezz, au moins deux sessions je pense.

**Comment by adriens** [comment]
Première revue de la prezz semaine dernière. :+1:

**Comment by adriens** [comment]
[Pour toi](https://twitter.com/r_FlutterDev/status/1596166526784376832) : 

![image](https://user-images.githubusercontent.com/5235127/204089753-8add560c-dd8d-4fe9-a60d-0e0708bde9d4.png)

**Comment by adriens** [comment]
Hello @lschaeffer313 , je viens de mettre à jour l'issue pour la rendre plus clean et claire quant aux attendus.

**Comment by adriens** [comment]
hello @lschaeffer313 , tu penses pouvoir livrer quand le contenu :grey_question:

**Comment by lschaeffer313** [comment]
Comme discuté plutôt vers la fin du mois.

**Comment by adriens** [comment]
Magnifique :star_struck: ... en plus y'a le lint mainteant :sunglasses:

**Comment by adriens** [comment]
Teasing fait ce jour cf [📢 Unboxing Domaine NC mobile v1.3.0 ](https://dev.to/optnc/unboxing-domaine-nc-mobile-v130-59pi)

**Comment by adriens** [comment]
- [:bird:  Tweet](https://twitter.com/rastadidi/status/1628185271337627648)
- [linkedINn](https://www.linkedin.com/posts/adrien-sales_mobile-app-deployment-automation-activity-7033949732716642304-J8Dx?utm_source=share&utm_medium=member_desktop)

**Comment by adriens** [comment]
:clap:
