### ISSUE TITLE
:loudspeaker: Call for testers : "I want you to test" :rocket: 

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#23]
## :grey_question: Contexte

Avant la publication de l'application sur le Play Store, il faut tester l'application pour : 

:bug:  Détecter les anomalies  (et les corriger) :sweat_smile: 
:people_holding_hands:  Construire une communauté
:open_hands:  Recruter des talents, des contributeurs
:bulb: Avoir de nouvelles idées

![My project-1(46)](https://user-images.githubusercontent.com/5235127/204073796-7057d5bd-4a6d-459d-9472-3738255f301e.png)

## :dart:  Actions

- [x] Faire un inspiraitonal
- [x] Publier l'inspirational twitter
- [x] Publier l'inspirational linkedIn
- [ ] Post DEV.to dédié
- [ ] Publier sur Teams interne
- [ ] Publier l'inspirational via affiche cafet
- [ ] Récupérer les adresses mails des testeurs

**Comment by lschaeffer313** [comment]
@adriens

**Comment by adriens** [comment]
Comment peut on récupéer l'a ppli pour l'installer ?

**Comment by lschaeffer313** [comment]
Il faut que je rajoute les adresses mail relié au compte google des différentes personnes.

**Comment by lschaeffer313** [comment]
Il est important que ce compte soit celui utilisé sur leur téléphone.

**Comment by lschaeffer313** [comment]
Et après il pourront accèder à l'application via ce lien https://play.google.com/store/apps/details?id=nc.laurent.domaine_nc_mobile

**Comment by adriens** [comment]
Ok, donc les adresses mails des comptes Gmail utilisés sur leur Android, c'est bien ça :grey_question:

**Comment by lschaeffer313** [comment]
C'est ça

**Comment by adriens** [comment]
Ok, je viens d'avoir une idée... je vois avec qulelqu'un qui pourrait etre super intéressé et qui pourrait nous mettre un coup boost. J'avance sur ce dernier point et après j'envoie une appel à volointaires bien clean

**Comment by adriens** [comment]
je vais avoir besoin d'un visuel sympa de l'appli, un écran

**Comment by lschaeffer313** [comment]
En voila deux pour le prix d'un 👌 :
![image](https://user-images.githubusercontent.com/28922072/194692865-363a52f4-8a16-4277-b28c-3ce4e70325ca.png)

![image](https://user-images.githubusercontent.com/28922072/194692847-3b054c50-e879-4dee-b8e8-5315663d0da2.png)

**Comment by adriens** [comment]
[Post](https://www.linkedin.com/posts/testeum_october-update-we-are-proud-to-announce-activity-6983924097181261824-2gPZ?utm_source=share&utm_medium=member_desktop)

![image](https://user-images.githubusercontent.com/5235127/194698782-3df4bc75-171a-47cc-a602-110c0c909b3e.png)

**Comment by adriens** [comment]
je kiffe tjs autant le label debug :star_struck:  @lschaeffer313

**Comment by adriens** [comment]
Inspirational en cours de dev....

**Comment by adriens** [comment]
[Tweet](https://twitter.com/rastadidi/status/1596379368523124736)

![image](https://user-images.githubusercontent.com/5235127/204074229-e0532aad-34c5-4391-b6af-087053ed092f.png)

**Comment by adriens** [comment]
[linkedIn](https://www.linkedin.com/posts/adrien-sales_nouvellecaledonie-android-earlyadopter-activity-7002146278771998721-ua-Y?utm_source=share&utm_medium=member_desktop)

![image](https://user-images.githubusercontent.com/5235127/204074372-21446923-de47-46fe-bb99-04569d39f152.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204074491-d76621aa-d78d-400c-ad8d-056d66f2e120.png)

**Comment by adriens** [comment]
Article DEV.to en cours de rédaction pour post semaine prochacine :rocket: @lschaeffer313

**Comment by HakumenNC** [comment]
Hola!

Ready up for tests 😉 : soutartronny@gmail.com

Merci 🙏🏽

**Comment by adriens** [comment]
> Hola!
> 
> Ready up for tests wink : [soutartronny@gmail.com](mailto:soutartronny@gmail.com)
> 
> Merci 🙏🏽

https://github.com/lschaeffer313/domaine-nc-mobile/pull/40

**Comment by HakumenNC** [comment]
Re :)

Appli bien installée sur le device, mais j'ai un souci dans la recherche, elle dans cet état de _"loading"_ sans renvoyer de résultat : 

* recherche sur : `opt`, `esport` et `enercal`

<img src="https://user-images.githubusercontent.com/2644417/204111463-52c156a9-53b9-470f-985b-d942ca0d1acd.jpg" width=200>

**Comment by adriens** [comment]
AH merde ç aveut dire que ça lagg côté API @lschaeffer313  https://rapidapi.com/opt-nc-opt-nc-default/api/domaine-nc

**Comment by adriens** [comment]
Je teste le back de suite....

**Comment by adriens** [comment]
Pb reproduit en effet :hankey:

**Comment by adriens** [comment]
J'analayse le truc

**Comment by adriens** [comment]
https://github.com/opt-nc/domaine-nc-api/issues/290#issuecomment-1328127494

![image](https://user-images.githubusercontent.com/5235127/204111835-486a3257-1273-4550-8835-247a126eebf3.png)

**Comment by adriens** [comment]
Oui c ça, le backend a déménagé cf https://github.com/opt-nc/domaine-nc-api/issues/290#issuecomment-1328127942

![image](https://user-images.githubusercontent.com/5235127/204111926-776da27e-03b4-4414-b25c-400c851709f2.png)

**Comment by adriens** [comment]
@HakumenNC tu peux fair eune issue sur ce projet stp ? Et me l'affecter ?

**Comment by adriens** [comment]
cf https://github.com/lschaeffer313/domaine-nc-mobile/issues/43

**Comment by adriens** [comment]
:information_source: @HakumenNC , grâce  à ton feedback : https://github.com/lschaeffer313/domaine-nc-mobile/issues/44

**Comment by adriens** [comment]
J'y suis les gars ! avec mon [`XCover 4`](https://www.samsung.com/ch_fr/business/smartphones/galaxy-xcover-4-g390f/sm-g390fzkaaut/) : 
![image](https://user-images.githubusercontent.com/5235127/204125424-70ed3871-c129-4adf-b30b-970cffe3b33e.png)

**Comment by adriens** [comment]
Normalement, demain, retour de l'API :muscle:

**Comment by adriens** [comment]
Les gars l'API est de retour 👍

**Comment by adriens** [comment]
@lschaeffer313 tu peux valider stp ? Su mon tel ça répond tjs pas...

**Comment by HakumenNC** [comment]
Idem, étrange car en testant directement sur rapid API, ça fonctionne

**Comment by adriens** [comment]
Donc faut dropper un bug @lschaeffer313 🔫 :trollface:

**Comment by adriens** [comment]
Moi je parie qu'on va voir une release atterrir discreto....

**Comment by adriens** [comment]
A mon avis... ça doit marcher sur sa machine :trollface:

**Comment by HakumenNC** [comment]
Une release ninja 🥷

**Comment by adriens** [comment]
> Une release ninja 🥷

Les meilleures !

**Comment by adriens** [comment]
cf #99
