### ISSUE TITLE
📜 Demande de la doc des release continue de documentation :repeat: 

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#24]

**Comment by adriens** [comment]
Yep @lschaeffer313 , avec plaisir, voici tous les détails : 

- [📜 API Documentation release automation with Github, redocly and Open API 🦾](https://dev.to/optnc/api-documentation-release-automation-with-github-redocly-and-open-api-f6h)
- [Domaine.NC as a Service in the cloud Series' Articles](https://dev.to/adriens/series/18166)

Enjoy :gift: :nerd_face:

**Comment by adriens** [comment]
https://dev.to/adriens/comment/226a8
