### ISSUE TITLE
📝 Modifier le README afin d'expliquer en quoi consiste ce projet

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#32]
Le README actuelle n'est pas explicite.
Il faudrait le modifier afin d'éclaircir à quoi correspond ce projet et le but de celui-ci

**Comment by adriens** [comment]
Oui, d'ailleurs, je dois préparer du contenu à ce sujet, et ce projet y est cité.

- :tv:  [Série DEV.to dédiée à l'API](https://dev.to/adriens/series/18166)
- :memo:  [Tanaloa](https://dev.to/optnc/talanoa-2022-the-power-of-data-visualization-1fgn)
- :popcorn:  [Storytelling video dédié à domaine.nc et où l'appli est citée](https://youtu.be/Ef8E69UhZ3w?t=5016)

Tu verras, tu y trouveras certaines de tes réalisations : 
![image](https://user-images.githubusercontent.com/5235127/202837480-46fb34ab-a036-4240-a2b3-b6fbd027a03b.png)

**Comment by adriens** [comment]
:point_right:  je ferai une version extended prochainement où je détaillerai davanatage les aspects techniques

**Comment by adriens** [comment]
:+1:
