### ISSUE TITLE
Virer l'option Wiki (le wiki c mal... le markdown sur la repo c mieux)

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#34]
![image](https://user-images.githubusercontent.com/5235127/204072723-43f69bc1-c46b-486f-afa5-4b5f236e7308.png)

**Comment by lschaeffer313** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/28922072/204078197-cb4425ad-df5d-4408-bb6b-2565a390ca56.png">

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204078571-998b74c0-dfb9-4382-a9af-e65663ae352b.png)
