### ISSUE TITLE
:rotating_light: Choisir une licence

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#37]
![image](https://user-images.githubusercontent.com/5235127/204076582-a24565fb-3917-4d7d-a19f-8a7885cb0323.png)

**Comment by lschaeffer313** [comment]
Done 😉

**Comment by adriens** [comment]
Yep
![image](https://user-images.githubusercontent.com/5235127/204078791-1331ea37-7ecc-4a90-8059-2cf41e1f7f1e.png)
