### ISSUE TITLE
:rotating_light: La recherche freeze sans aboutir :rotating_light: 

### ISSUE THREAD

**Issue by HakumenNC** [lschaeffer313/domaine-nc-mobile#43]
## Contexte

Un souci dans la recherche, elle dans cet état de _"loading"_ sans renvoyer de résultat :

recherche sur : `opt`, `esport` et `enercal`

<img src="https://user-images.githubusercontent.com/2644417/204111463-52c156a9-53b9-470f-985b-d942ca0d1acd.jpg" width=200>

### Résultat attendu

La liste présente les résultats de la recherche

**Comment by adriens** [comment]
Yes, pb identifé côté back.

![image](https://user-images.githubusercontent.com/5235127/204112200-2fbf013c-377a-40f8-9688-979cff1c5b71.png)

![image](https://user-images.githubusercontent.com/5235127/204112206-3471d29e-2998-44f0-a97f-0292f2ff399e.png)

![image](https://user-images.githubusercontent.com/5235127/204112239-cdda784d-900c-48a0-ae8f-c4cbe0196c33.png)

**Comment by adriens** [comment]
En attente du fix de l'url du backend par @pluaki 
On reviendra vers toi @HakumenNC demain pour valider le retour en mode normal
:pause_button:

**Comment by HakumenNC** [comment]
Oki 🙏🏽

**Comment by adriens** [comment]
:pause_button:

**Comment by adriens** [comment]
Ca freeze toujours, comme si l'api ne réussissaint pas à être jointe

![image](https://user-images.githubusercontent.com/5235127/204224985-1991978a-f5c5-4787-8d8f-660bd4b79d90.png)

**Comment by adriens** [comment]
... alors que l'API est bien toujours là

![image](https://user-images.githubusercontent.com/5235127/204225103-869c5663-77f4-49e6-b989-8ea6136cd0ed.png)

**Comment by adriens** [comment]
yes, voila @HakumenNC 

cf https://docs.flutter.dev/development/data-and-backend/networking : 

<manifest xmlns:android...>
 ...xml
 <uses-permission android:name="android.permission.INTERNET" />
 <application ...
</manifest>

<manifest xmlns:android...>
 ...
 <uses-permission android:name="android.permission.INTERNET" />
 <application ...
</manifest>

**Comment by adriens** [comment]
Android apps must [declare their use of the internet](https://developer.android.com/training/basics/network-ops/connecting) in the Android manifest (AndroidManifest.xml ):

**Comment by adriens** [comment]
@lschaeffer313 : tu as pu reproduire sur l'APK à priori

**Comment by lschaeffer313** [comment]
Yes

**Comment by lschaeffer313** [comment]
D'après @HakumenNC cela pourrait provenir d'un problème de droit.
Je vais tester ça

**Comment by adriens** [comment]
Good, oui, on avait eu ça déja. C'est assez surprenant.

Mais déja, tu as pu reprodure, ça va le faire

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204226888-b40d4f1c-0d06-43db-9fad-784b8f78a9b3.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204228851-4cf5f6b1-9c0a-4c1a-8738-7c5eb78e848c.png)

**Comment by adriens** [comment]
c parti https://github.com/lschaeffer313/domaine-nc-mobile/actions/runs/3562973041/jobs/5985238935

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204229108-c2c56c17-8b2a-46d9-9cb1-16a510d27625.png)

**Comment by adriens** [comment]
:heavy_check_mark: 
![image](https://user-images.githubusercontent.com/5235127/204230190-3b5e1ffb-667a-4215-9e15-bf767131988e.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204230561-27aa387c-2962-47de-86bb-8d1718ab23f9.png)

**Comment by adriens** [comment]
@lschaeffer313 , dis nous quand c modéré par Google et on teste avec @HakumenNC  :rocket: :muscle: :nerd_face:

**Comment by HakumenNC** [comment]
Bravo la team de choc 👊🏽

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204237304-c3b42476-130c-44d6-af1a-e540e924e42f.png)

**Comment by lschaeffer313** [comment]
La mise à jour est en ligne :
<img width="663" alt="image" src="https://user-images.githubusercontent.com/28922072/204244090-3517b26b-93f4-45ba-986b-df428703578d.png">

**Comment by adriens** [comment]
je pull...

**Comment by adriens** [comment]
:drum:

**Comment by adriens** [comment]
![Screenshot_20221128-204736](https://user-images.githubusercontent.com/5235127/204246598-d153966f-0184-4f02-979e-e12119ab4c4d.jpg)

**Comment by adriens** [comment]
:rocket: 
![image](https://user-images.githubusercontent.com/5235127/204246975-4f2153c0-f75a-47f4-9996-1ab40d3bfc42.png)

![image](https://user-images.githubusercontent.com/5235127/204246998-32e4a717-814a-4a27-b77e-fc85b6cafbba.png)

![image](https://user-images.githubusercontent.com/5235127/204247022-201ae34b-920a-4fb3-a1e0-1750f4c8b479.png)

![image](https://user-images.githubusercontent.com/5235127/204247050-cabc5ae7-0334-4120-adf9-6b2b9e92cd9c.png)

**Comment by adriens** [comment]
:100: :ok: pour moi.

Et pour toi @HakumenNC :grey_question:

**Comment by adriens** [comment]
@spencer-forrest-opt : le cacher serverside... :muscle: :zap:

**Comment by HakumenNC** [comment]
Fonctionne du feu de dieu

Merci!

**Comment by spencer-forrest-opt** [comment]
> @spencer-forrest-opt : le cacher serverside... 💪 ⚡

I have to cache some more data serverside ?

**Comment by adriens** [comment]
Nope @spencer-forrest-opt , it works perfectlu fine : the UX on the mobile side is :ok_man:

**Comment by adriens** [comment]
> Fonctionne du feu de dieu
> 
> Merci!

Yes, j'aurai pas dit mieux :pray:

**Comment by adriens** [comment]
> Fonctionne du feu de dieu
> 
> Merci!

@HakumenNC 
![image](https://user-images.githubusercontent.com/5235127/204374936-b254161f-3190-4361-8e39-870794a0fdf4.png)
