### ISSUE TITLE
:shield:  Mieux gérer la non dispo du back

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#44]
# :grey_question: Description

Actuellement quand le back ne répond pas du tout (timeout), l'écran freeze cf feedback de @HakumenNC : 

![image](https://user-images.githubusercontent.com/5235127/204112362-a8a340c8-18b0-4aaf-b09b-94795db86f49.png)

# :tickets: Issue liées

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/43

**Comment by lschaeffer313** [comment]
Je pense qu'un timeout avec un message d'erreur plus concis pourra aider à l'avenir si le cas se représente

**Comment by adriens** [comment]
> Je pense qu'un timeout avec un message d'erreur plus concis pourra aider à l'avenir si le cas se représente

Tout à fait :+1:

**Comment by lschaeffer313** [comment]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/28922072/204114681-67a212e3-67a1-4182-b791-4519be679e1c.png">

**Comment by adriens** [comment]
fixé dans https://github.com/lschaeffer313/domaine-nc-mobile/releases/tag/v1.0.6

**Comment by lschaeffer313** [comment]
Apparemment il y a un problème avec l'une des dépendances qui fait que la production de l'artifact rentre en erreur.
Je vais créer une issue pour le créateur de la dépendance.

**Comment by adriens** [comment]
Yes, oublie pas de la linker ici :pray:

**Comment by lschaeffer313** [comment]
👉 https://github.com/ja2375/add_2_calendar/issues/121

**Comment by adriens** [comment]
:heavy_check_mark:  vu

- https://github.com/ja2375/add_2_calendar/issues/121
