### ISSUE TITLE
💩  Logo et nom app mobile moches 😆 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#47]
![image](https://user-images.githubusercontent.com/5235127/204183463-37becff3-bb44-41ff-9f38-00ee32e7939a.png)

**Comment by adriens** [comment]
Si on veut une belle démo video, faudrait faire propre

**Comment by adriens** [comment]
Je vois pas de nouveau logo ni le changement de nom :thinking:

**Comment by lschaeffer313** [comment]
Tu es sur qu'elle version ?
La 1.1.0 n'a pas de logo.
J'ai refais une autre release (1.2.0) qui contient justement le logo et le dark mode par défaut

**Comment by adriens** [comment]
Yep, ça colle impec, je suis bien en [`v1.1.0`](https://github.com/lschaeffer313/domaine-nc-mobile/releases/tag/v1.1.0) : 

![image](https://user-images.githubusercontent.com/5235127/208290380-388f35fb-fb05-405a-a8ed-b98b57fc95d3.png)

**Comment by adriens** [comment]
Fixé dans la dernière version :clap: :pray:
