### ISSUE TITLE
:cinema:  Video de demo pour v1.0.7 :cinema: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#53]
# :grey_question: Contexte

La [1.0.7](https://github.com/lschaeffer313/domaine-nc-mobile/compare/v1.0.6...v1.0.7) a été releasée hier et permet de disposer d'un première version fonctionnelle : 

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/43#issuecomment-1328853747

On peut dès à présent : 

:mag_right:  Chercher en mode full text un domaine
:bookmark_tabs:  Consulter les détails d'un domaine
:calendar:  Ajouter un reminder au calendrier dans le cloud de son choix **afin de ne jamais rater une expiration**

:point_right: **Il est dont temps de valoriser ce scénario avec une démo video** :point_left: 

# :dart: Actions

Produire une video sur téléphone où l'utilisateur : 

- [x] Cherche son appli (visu du logo sur le bureau du téléphone)
- [x] Ouvre l'appli
- [x] Cherche un nom de domaine
- [x] Consulte les détails
- [x] Ajouter le reminder à son calendrier
- [x] Ferme l'appli
- [x] Consulte son calendrier pour vérifier que le remonder est bien là
- [x] Fin de la demo

Puis : 

- [x] Fournir la video (`.mp4`)
- [ ] Faire un Post DEV.to dédié
- [ ] Communiquer sur les réseaux sociaux : Twitter, linkedIn

# :tickets: Issues liées

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/23
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/43
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/32
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/47

**Comment by adriens** [comment]
Cut de la video en cours,...

**Comment by HakumenNC** [comment]
TODO : refaire la vidéo avec l'icone et le nom revus dans l'idéal

**Comment by adriens** [comment]
> TODO : refaire la vidéo avec l'icone et le nom revus dans l'idéal

On en fera une autre et ce sera pour annocner l'arrver de l'cone 🚀

**Comment by adriens** [comment]
> TODO : refaire la vidéo avec l'icone et le nom revus dans l'idéal

cf https://github.com/lschaeffer313/domaine-nc-mobile/issues/47
