### ISSUE TITLE
:rotating_light: 🐛  Bug affichage > Impossible de lire Serveur DNS dans certains cas :rotating_light: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#54]
Pour reproduire : 

Chercher Redstone
![image](https://user-images.githubusercontent.com/5235127/204655480-5c46da80-cccf-4e63-be0f-41d371080d09.png)

**Comment by lschaeffer313** [comment]
Test sur Bebunk :
 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/28922072/204771174-b0ac9559-c894-4743-82f4-ae64c39b14be.png">

**Comment by adriens** [comment]
Je teste demain : 


- la maj
- l'affichage

**Comment by adriens** [comment]
Je fais comment pour avoir la MAJ ?

**Comment by adriens** [comment]
J'ai pas de notif, rien :thinking:

**Comment by adriens** [comment]
OK, faut y aller par l'url

donc:

1. ALler sur README
2. Section des liens utiles
3. Cliquer
4. Mettre à jour
![image](https://user-images.githubusercontent.com/5235127/204917481-7455b596-458a-4c3d-b18e-ec8f7be33af1.png)

**Comment by adriens** [comment]
Je passe au test...

**Comment by adriens** [comment]
C'est mieux, je scrolle u npeit peut et ça passe

![image](https://user-images.githubusercontent.com/5235127/204917842-197c5ecc-c440-46c4-9b6b-268c61d98613.png)

**Comment by adriens** [comment]
https://github.com/lschaeffer313/domaine-nc-mobile/discussions/68
