### ISSUE TITLE
👐  Nouvel invité [MAOUDJ Matthieu] sur la Track Beta 🚀 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#56]
# Contexte

L'app sur le store publique est toujours sur la version buggée (timeout).

# 🎯 Action

Inviter `matmao35@gmail.com` sur la track Beta

**Comment by lschaeffer313** [comment]
Yes je vais l'inviter de ce pas.

**Comment by lschaeffer313** [comment]
Ajouté 
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/28922072/204682249-80210922-6ae3-4d55-a2e3-283cdc2e3ac9.png">

**Comment by adriens** [comment]
C'est lui a levé l'incident cf

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/57

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/204687210-1408c687-c038-4a05-ac35-a86efa46eeb4.png)

**Comment by adriens** [comment]
je prends la suite :+1:

**Comment by adriens** [comment]
Et toi @sverolle , tu veux pas en être :grey_question:

**Comment by sverolle** [comment]
> Et toi @sverolle , tu veux pas en être ❔

Mais sssiiii ! Comment on fait ?

**Comment by adriens** [comment]
Enorme !!!
