### ISSUE TITLE
:shield: Dependabot now supports security updates for Dart and Flutter

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#66]
[Tweet](https://twitter.com/GHchangelog/status/1598008473760956439) : 

![image](https://user-images.githubusercontent.com/5235127/204888334-23cb803d-07c0-4d7b-9349-3ce421ae4818.png)

[Blog Post](https://github.blog/changelog/2022-11-30-dependabot-now-supports-security-updates-for-dart-and-flutter-apps-that-use-pub-packages/) : 

![image](https://user-images.githubusercontent.com/5235127/204888476-50fe17d8-068b-4ceb-b763-7c7e6b5d62a3.png)

**Comment by lschaeffer313** [comment]
Ajouté :
<img width="847" alt="image" src="https://user-images.githubusercontent.com/28922072/204997371-27d43091-ed55-40f4-ae41-f49fb23c6450.png">

**Comment by adriens** [comment]
BIM ! Méchant le time to market :muscle: :shield:
