### ISSUE TITLE
:calendar:  Ajouter la possibilité de rajouter un rappel pour un domaine :bell: 

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#7]
## Action
 Je veux pouvoir créer un évènement dans mon calendrier (Smartphone, PC ou autre) à partir de la page d'un domaine.
## Besoin 
Me rappeler de la date d'expiration de mon domaine afin de le renouveler.

**Comment by adriens** [comment]
Yes j'ai piné l'issue

**Comment by lschaeffer313** [comment]
@adriens je ferais une vidéo Lundi présentant l'app à notre communauté 😆.

**Comment by adriens** [comment]
WTF !!! Déja ?!!! C'est de la bombe mec :open_mouth: Hâte d'en faire le Story telling :clap:

**Comment by lschaeffer313** [comment]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/28922072/190931564-6742311c-2c25-4750-aefe-fa47a348c696.png">

**Comment by adriens** [comment]
:ok_man:

**Comment by adriens** [comment]
YES :heavy_heart_exclamation:
