### ISSUE TITLE
Inviter Vincent Lavergne (aka. kiou98) sur la beta

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#70]
[Vincent Lavergne](https://www.linkedin.com/in/vincent-lavergne/)
@tealforge.com

`***@***.***`

![image](https://user-images.githubusercontent.com/5235127/204981104-298f2869-92f7-45f7-8948-05edad499f38.png)

cf : 

- https://github.com/lschaeffer313/domaine-nc-mobile/discussions/69#discussioncomment-4280130

https://github.com/kiou98

**Comment by lschaeffer313** [comment]
Ajouté :
<img width="923" alt="image" src="https://user-images.githubusercontent.com/28922072/204992360-748c8ce4-16db-4769-be66-d5137ffea76d.png">
