### ISSUE TITLE
About : ajouter Android

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#79]
![image](https://user-images.githubusercontent.com/5235127/205480992-cd01b68e-f7b9-4400-a7e2-14ba30a2cef2.png)

**Comment by lschaeffer313** [comment]
<img width="325" alt="image" src="https://user-images.githubusercontent.com/28922072/206885042-9e15ce94-1201-4027-806f-05d240e7e345.png">

**Comment by adriens** [comment]
:zap:
