### ISSUE TITLE
:grey_question:  Page "About"

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#8]
Une page dans l'app avec : 

- La version
- L'API utilisée (RapidAPI)
- Les contributeurs actifs

**Comment by lschaeffer313** [comment]
@adriens pour la liste des contributeurs je mets directement le bureau GLIA ou une liste de personnes ?

**Comment by adriens** [comment]
L'idée est de pointer vers genre un markdown sur la repo publique ? (pas de maintenance coté appli et nativement reponsive via GH) ?

**Comment by lschaeffer313** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/28922072/202837016-ceae50f9-77a9-4447-beb0-830eaf7c6bc7.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/28922072/202837136-8f58855e-ef6e-4471-8a8e-87c2c6c81606.png">

**Comment by adriens** [comment]
Te casse pas la tête, passe par un `CONTRIBUTORS.md`

**Comment by lschaeffer313** [comment]
Ah pas bête, je vais voir ce que je peux faire

**Comment by lschaeffer313** [comment]
Ok ça marche

**Comment by adriens** [comment]
Idem pour l'API, on aura plus de latitude, on fera un md dédié aussi, je te ferai la PR même

**Comment by adriens** [comment]
Comme la repo est publique c'est super facile en vrai :bulb:

**Comment by adriens** [comment]
Pour les contributeurs, voila : 

- https://github.com/lschaeffer313/domaine-nc-mobile/pull/38
- https://github.com/lschaeffer313/domaine-nc-mobile/issues/36

**Comment by adriens** [comment]
Le README est maintenant assez complet, tu peux pointer dessus cf : 

- https://github.com/lschaeffer313/domaine-nc-mobile/pull/61
- https://github.com/lschaeffer313/domaine-nc-mobile/pull/55

**Comment by adriens** [comment]
:zap:
