### ISSUE TITLE
🫥 Ajout d'un dark mode 🫥

### ISSUE THREAD

**Issue by lschaeffer313** [lschaeffer313/domaine-nc-mobile#81]
# Problème
L'utilisateur a l'habitude de choisir sur son device le thème sombre ou clair qui permet aux applications de changer leur couleur en fonction

# A faire
Implémenter un thème sombre avec un changement entre les deux thème en fonction du thème utilisé sur le device

**Comment by lschaeffer313** [comment]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/28922072/206887894-f9228fab-ae80-4a36-b0a9-9128548d87cf.png">
<img width="352" alt="image" src="https://user-images.githubusercontent.com/28922072/206887903-6298842b-b58e-4442-b559-092ea27ae0b9.png">

**Comment by lschaeffer313** [comment]
J'ai aussi changé la couleur du statut en jaune pour mieux refléter la couleur principale de l'appli

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/206893211-5f487d7a-0d18-47e8-bcbc-f5a64747386f.png)

**Comment by adriens** [comment]
Peuaahhh, j'adore et c'est super lisible :heavy_heart_exclamation:
