### ISSUE TITLE
:fearful: Ca freeze à nouveau :question: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#84]
Protocole

1. Déinstaller
2. Aller sur le README de la repo
3. Cliquer sur le badge du playstore
4. Lancer une recherche
5. Constater le freeze

Et la recherche full ne répond plus...

Je suis le seul ?

**Comment by adriens** [comment]
:heavy_check_mark: API

**Comment by lschaeffer313** [comment]
@HakumenNC tu as le même soucis ?

**Comment by lschaeffer313** [comment]
Pas de soucis de mon côté non plus.
J'ai rebuilder l'appli en mode release pour être sur.

**Comment by adriens** [comment]
Je reteste...

**Comment by adriens** [comment]
nope, ça freeze toujours :cry:

**Comment by adriens** [comment]
Du coup... en me balladant sur le store, je me rends compte que : 

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/85

**Comment by adriens** [comment]
Et je suis en `1.0.2` @lschaeffer313

**Comment by adriens** [comment]
ALors que je viens tt juste d' leinstaller :hankey:

**Comment by adriens** [comment]
Rien faire : je désinstalle et réinstalle... je me prends toujours la `1.0.2` :fearful:

**Comment by HakumenNC** [comment]
C'est bien la bêta que tu récupères?

**Comment by adriens** [comment]
url de la beta ?

**Comment by adriens** [comment]
(car non, pas de mention de a beta)

**Comment by adriens** [comment]
Je suis le README, c'est mon protocole

**Comment by adriens** [comment]
Du cuop ça veut dire que la version officielle non beta est plus buggée que la beta :trollface:

**Comment by HakumenNC** [comment]
Le lien du README me renvoie bien sur la béta

**Comment by adriens** [comment]
Alors je suis plus sur la beta.... je vais me plaindre au support :loudspeaker:

**Comment by HakumenNC** [comment]
D'ailleurs la version "officielle" n'a pas été retirée du store?

**Comment by adriens** [comment]
pas sur mon cloud internet... ou alors je suis dans une faille temporelle !

**Comment by adriens** [comment]
bref comdab... "ça marche sur on tel" de @HakumenNC

**Comment by HakumenNC** [comment]
Reproduit.

**Sur desktop + connecté à un compte Google via le navigateur**, le lien renvoie vers la 1.0.2 (non béta).
Sans la connexion au compte google, le lien renvoie sur une page 404.

Si le clic sur le lien se fait à partir du **navigateur web ou de l'appli `github `depuis un smartphone**, le lien renvoie vers la beta.

Vous avez dit mystique?

**Comment by adriens** [comment]
Bon ben ça confirme la stratégie en mode brutal : 

:gun: beta
:rocket: main ouverte


:smile_cat: @lschaeffer313

**Comment by lschaeffer313** [comment]
En cours de déploiement de la version 1.10.0 en prod.
Je fait le ménage côté Google Play pour qu'il n'y ait plus de béta

**Comment by lschaeffer313** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/28922072/208280356-aaf73817-6dc6-48a0-9622-260f631ee321.png">

**Comment by adriens** [comment]
Yes, dès que c'est dispo, je dropperai le résulat du test ici :ok_man:

**Comment by lschaeffer313** [comment]
Version 1.1.0 déployé en Production 
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/28922072/208283300-9d9601c0-16dc-4f25-bfe6-e6694228e0f0.png">

**Comment by adriens** [comment]
Yep et j'ai bien eu la notification

![image](https://user-images.githubusercontent.com/5235127/208288449-d1aa5f88-2a2c-463b-a5d7-50b23e886f87.png)

![image](https://user-images.githubusercontent.com/5235127/208288453-fd511119-84f0-447d-b90a-d0bc02c26985.png)

![image](https://user-images.githubusercontent.com/5235127/208288455-6c3b7761-cce0-42bf-b780-3459261e59e0.png)

**Comment by adriens** [comment]
Mais y'a pas le thème dark par défaut, c'est normal @lschaeffer313 ?
