### ISSUE TITLE
:bulb: Ca serait cool que dans le preview du store ce soit le mode dark, non ?

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#85]

**Comment by lschaeffer313** [comment]
Mise à jour faites cela devrait prendre un moment pour la mise à jour sur le store.
<img width="952" alt="image" src="https://user-images.githubusercontent.com/28922072/208283774-5779a42a-689c-4db4-b474-9761c2b7cec6.png">

**Comment by lschaeffer313** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/28922072/208287597-f07208d1-502e-4d30-8b25-34809508aaeb.png">

**Comment by adriens** [comment]
Stylé :sunglasses:
