### ISSUE TITLE
:shopping:  Pusher sur les stores

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#9]

**Comment by lschaeffer313** [comment]
En attente de validation côté Google :
<img width="580" alt="image" src="https://user-images.githubusercontent.com/28922072/194682957-bcda8f87-ea46-4440-b71a-17e725d8635d.png">

Et déployé via Fastlane 😎 :
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/28922072/194682991-3dcfa237-09c8-4024-a778-56934f1c1e13.png">

**Comment by lschaeffer313** [comment]
🚀 
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/28922072/194683267-ab0b07b5-ebd4-491b-9541-e1d49a30412a.png">

**Comment by lschaeffer313** [comment]
Je l'enlève des stores pour le moment car l'application n'est pas prêt.

**Comment by adriens** [comment]
Joli, très joli :clap:

**Comment by adriens** [comment]
J'ai lancé l'appel à testeurs ce jour : 

- https://github.com/lschaeffer313/domaine-nc-mobile/issues/23

**Comment by adriens** [comment]
@lschaeffer313 , tu repousses quand sur le store ? Les gens sont intéressés comme [Philippe REAUD ](https://www.linkedin.com/in/philippe-reaud/) : 

![image](https://user-images.githubusercontent.com/5235127/204077443-e3030255-8e6d-4ef5-9ee2-d875f3b9daac.png)

**Comment by lschaeffer313** [comment]
Pas pour le moment.
Par contre je peux poussé une bétaillère publique désireux de tester l'appli 😁

**Comment by adriens** [comment]
Yes, stp, y'a pas mal d'intéressés :100:

**Comment by adriens** [comment]
GO pour la bêta publique alors :rocket:

**Comment by adriens** [comment]
@lschaeffer313 , on a un premier client :1st_place_medal: cf : 

- https://github.com/lschaeffer313/domaine-nc-mobile/pull/38#issuecomment-1328000882

**Comment by lschaeffer313** [comment]
En review côté Google pour la bêta publique :
<img width="449" alt="image" src="https://user-images.githubusercontent.com/28922072/204079319-86783bb4-8f3d-44d3-ac45-a280a6e018d4.png">

**Comment by adriens** [comment]
Yes, là faut être patient :hourglass_flowing_sand:

**Comment by adriens** [comment]
I'm in !

https://play.google.com/apps/testing/nc.laurent.domaine_nc_mobile

![Screenshot_20221126-202241_Chrome](https://user-images.githubusercontent.com/5235127/204081751-a62bc6dd-df2a-4465-8c55-9500ed0129a9.jpg)

**Comment by lschaeffer313** [comment]
Let the test begin 🧪🧪🧪

**Comment by lschaeffer313** [comment]
En cours de publication

**Comment by lschaeffer313** [comment]
Version 1.1.0 déployé en Production
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/28922072/208283316-bf440a81-1616-4914-8a79-09dab0c46b49.png">

**Comment by adriens** [comment]
:rocket:
