### ISSUE TITLE
🔍 Score d'accessibilité 👓 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#96]
# 🎯  Action

Avec l'application [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor), auditer l'accessibillité de l'application

# 🔖 Ressources

- [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor)
- https://color.review/

**Comment by adriens** [comment]
👉  Merci @sverolle pour le tip

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/209503943-e5bc6131-c021-4bbe-bb57-3ca6e49d1f7e.png)

**Comment by adriens** [comment]
![image](https://user-images.githubusercontent.com/5235127/209503954-0f833baf-f55f-4afd-b647-950024320c54.png)

**Comment by adriens** [comment]
woila @lschaeffer313 @HakumenNC

**Comment by HakumenNC** [comment]
En regardant les différentes captures d'exemples du scanner du Store, j'ai l'impression qu'il n'arrive pas à détecter les éléments de l'écran, pareil sur mon tel.

Exemple

<img src="https://user-images.githubusercontent.com/2644417/209893248-29a45d9d-c4de-45b9-9207-e49d9a2a5226.png" alt="img" width="400"/>

**Comment by adriens** [comment]
C'est balo ! Ptet que en debug sur un iPhone ça marcherait mieux ? :trollface:  @lschaeffer313

**Comment by adriens** [comment]
Des ressources intéressantes sur le sujet @sverolle  @lschaeffer313 : https://dev.to/kathryngrayson/understanding-color-and-accessibility-n6p
