### ISSUE TITLE
:people_holding_hands:   Lancer campagne Testeum  :champagne: 

### ISSUE THREAD

**Issue by adriens** [lschaeffer313/domaine-nc-mobile#99]
# :grey_question: Contexte

Le [MVP](https://github.com/lschaeffer313/domaine-nc-mobile/milestone/1) a été atteint.

Grâce à [Zoe](https://www.linkedin.com/in/zoe-thivet/), le projet va bénéficier d'une campagne de crowd testing offerte par [Testeum](https://testeum.com/) :heavy_heart_exclamation:

:point_right:  Le but de ticket est de détailler et valider certains points avant de lancer la campagne. 

# :dart:  Actions

- [x] :calendar:  Fixer une date
- [x] Figer le [MVP](https://github.com/lschaeffer313/domaine-nc-mobile/milestone/1)
- [x] :people_holding_hands: Nous rencontrer en présenciel lors d'un pot de kickoff
- [x] :cold_face: Règle du jeu liée aux changement durant cette période de test (proposition de freeze sur une version bien spécifique)
- [x] :student: Nous faire expliquer par Zoe ce qu'il faut qu'on lui fournisse
- [x] :tickets: Détail du canal des feedbacks : comment récupérer les issues, etc... en sortie de teseum (et proposition d'évolution Testeum)
- [x] :warning: Aborder le sujet de la stabilisation de l'API afin que la partie back soit stable (ne pas renouveler #100 )

**Comment by adriens** [comment]
:information_source: @HakumenNC :rocket:

**Comment by adriens** [comment]
:beer: Jeudi prochain 17h00 bout du monde ?

**Comment by adriens** [comment]
:point_right: Date fixée à **jeudi 05 Janvier 2023,, 17h00** au [Bout du monde](https://www.facebook.com/LBDM.Events/)

**Comment by adriens** [comment]
On déménage l'API pour un dns fixe semaine prochaine

**Comment by adriens** [comment]
Woila pour le lancement des hostilités 😆 
https://github.com/lschaeffer313/domaine-nc-mobile/issues/105#issuecomment-1370515927

**Comment by adriens** [comment]
:pray:  @lschaeffer313 fais péter les photos/video de la super session en terrrase hier :sunglasses:

**Comment by lschaeffer313** [comment]
![image](https://user-images.githubusercontent.com/28922072/210922504-39db2971-8fb4-47de-b3e5-6294769875e3.jpeg)![Uploading 210922506...]

**Comment by adriens** [comment]
[linkedIn](https://www.linkedin.com/posts/adrien-sales_afterwork-womenintech-noumea-activity-7017359744457736192-dly6?utm_source=share&utm_medium=member_desktop)

![image](https://user-images.githubusercontent.com/5235127/211132583-b74e3d06-c6e6-49fd-9cc3-3ae79fe0a33c.png)

![My project-1(61)](https://user-images.githubusercontent.com/5235127/211132592-db833050-3bcc-4f47-a83c-de53eb9b6515.png)

**Comment by adriens** [comment]
L'API est en cours de stabilisation. Probablement lundi.

:point_right: Je vous tiens au jus

**Comment by adriens** [comment]
API stabilisée 🚀

**Comment by adriens** [comment]
C'est parti pour https://github.com/lschaeffer313/domaine-nc-mobile/issues/114

**Comment by lschaeffer313** [comment]
Campagne lancée !!!
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/28922072/211766709-29109498-496a-4745-8aff-b0d42494ee72.png">

**Comment by adriens** [comment]
Magnifique @lschaeffer313 , punaise ça gère grave cette semaine :muscle: :people_holding_hands: ... du front au back, y'a que des champions dans cette team de dingues :heavy_heart_exclamation:
